### ISSUE TITLE
init error windows and ubuntu

### ISSUE THREAD

**Issue by m7jalta** [ox01024/FofaSearch#1]
Traceback (most recent call last):
  File "C:\Users\MSI\Desktop\FofaSearch\Fofa_search.py", line 87, in <module>
    main()
  File "C:\Users\MSI\Desktop\FofaSearch\Fofa_search.py", line 79, in main
    args.func(args)
  File "C:\Users\MSI\Desktop\FofaSearch\src\core.py", line 26, in init
    initialized = getResponse(api) #Account verification
  File "C:\Users\MSI\Desktop\FofaSearch\src\requests.py", line 28, in getResponse
    message = 'Username:' + Response_json['username'] + '\n'
KeyError: 'username'

**Comment by ox01024** [comment]
![image](https://user-images.githubusercontent.com/52460705/123024993-8c17d400-d40c-11eb-9bec-9dda9af0e882.png)
